const List<String> countriesList = [
  // Cities in Egypt
  'cairo',
  'alexandria',
  'shibin el kom',
  'giza',
  'shubra el-kheima',
  'port said',
  'suez',
  'luxor',
  'al-mansura',
  'el-mahalla el-kubra',
  'tanta',
  'asyut',
  'ismailia',
  'fayyum',
  'zagazig',
  'aswan',
  'damietta',
  'damanhur',
  'al-minya',
  'beni suef',
  'qena',
  'sohag',
  'hurghada',
  '6th of october city',
  'banha',
  'kafr el-sheikh',
  'arish',
  'mallawi',
  '10th of ramadan city',
  'bilbeis',
  'marsa matruh',
  'idku',
  'mit ghamr',
  'al-hamidiyya',
  'desouk',
  'qalyub',
  'abu kabir',
  'kafr el-dawwar',
  'girga',
  'akhmim',
  'matareya',
  'kom ombo',
  'kasr el-aini',
  'zifta',
  'kom hamada',
  'toukh',
  'qaha',
  'armant',
  'ashmun',
  'al-ibrahimiyah',
  'dar as salam',
  'itay el-barud',
  'faraskur',
  'ash shuhada',
  'dairut',
  'siwa oasis',

  // Common countries around the world
  'usa',
  'china',
  'india',
  'brazil',
  'russia',
  'japan',
  'mexico',
  'germany',
  'france',
  'united kingdom',
  'italy',
  'south korea',
  'spain',
  'canada',
  'indonesia',
  'australia',
  'netherlands',
  'saudi arabia',
  'turkey',
  'switzerland',
  'iran',
  'thailand',
  'poland',
  'sweden',
  'belgium',
  'norway',
  'austria',
  'uae',
  'israel',
  'egypt',
  'denmark',
  'singapore',
  'malaysia',
  'south africa',
  'philippines',
  'finland',
  'ireland',
  'portugal',
  'greece',
  'new zealand',
  'qatar',
  'ukraine',
  'colombia',
  'argentina',
  'algeria',
  'vietnam',
  'chile',
  'peru',
  'czech republic',
  'romania',
  'egypt',
  'morocco',
  'nigeria',
  'venezuela',
  'iraq',
  'hungary',
  'kuwait',
  'oman',
  'belarus',
  'slovakia',
  'bulgaria',
  'croatia',
  'bosnia and herzegovina',
  'serbia',
  'estonia',
  'slovenia',
  'lithuania',
  'latvia',
  'tunisia',
  'azerbaijan',
  'lebanon',
  'uzbekistan',
  'kazakhstan',
  'cyprus',
  'costa rica',
  'dominican republic',
  'panama',
  'uruguay',
  'sri lanka',
  'tanzania',
  'syria',
  'jordan',
  'burma (myanmar)',
  'ghana',
  'yemen',
  'afghanistan',
  'botswana',
  'cameroon',
  'ivory coast',
  'mozambique',
  'zambia',
  'malawi',
  'nepal',
  'sudan',
  'albania',
  'armenia',
  'moldova',
  'mongolia',
  'north korea',
  'pakistan',
  'saudi arabia',
  'ethiopia',
  'uganda',
  'rwanda',
  'mali',
  'senegal',
  'madagascar',
  'cote d ivoire',
  'angola',
  'burkina faso',
  'niger',
  'chad',
  'guinea',
  'benin',
  'tunisia',
  'somalia',
  'zimbabwe',
  'namibia',
  'south sudan',
  'liberia',
  'mauritania',
  'sierra leone',
  'eritrea',
  'swaziland',
  'gabon',
  'haiti',
  'djibouti',
  'lesotho',
  'gambia',
  'guinea-bissau',
  'equatorial guinea',
  'mauritius',
  'sao tome and principe',
  'comoros',
  'seychelles',
  'afghanistan',
  'bhutan',
  'brunei',
  'cambodia',
  'east timor',
  'fiji',
  'kiribati',
  'laos',
  'maldives',
  'marshall islands',
  'micronesia',
  'mongolia',
  'nauru',
  'palau',
  'papua new guinea',
  'samoa',
  'solomon islands',
  'tonga',
  'tuvalu',
  'vanuatu',
  // Common cities around the world
  'new york',
  'los angeles',
  'chicago',
  'houston',
  'phoenix',
  'philadelphia',
  'san antonio',
  'san diego',
  'dallas',
  'san jose',
  'austin',
  'jacksonville',
  'fort worth',
  'columbus',
  'charlotte',
  'san francisco',
  'indianapolis',
  'seattle',
  'denver',
  'washington',
  'boston',
  'el paso',
  'nashville',
  'detroit',
  'oklahoma city',
  'portland',
  'las vegas',
  'memphis',
  'louisville',
  'baltimore',
  'milwaukee',
  'albuquerque',
  'tucson',
  'fresno',
  'sacramento',
  'kansas city',
  'long beach',
  'mesa',
  'atlanta',
  'colorado springs',
  'omaha',
  'raleigh',
  'miami',
  'oakland',
  'tulsa',
  'minneapolis',
  'cleveland',
  'wichita',
  'arlington',
  'new orleans',
  'bakersfield',
  'tampa',
  'honolulu',
  'anaheim',
  'aurora',
  'santa ana',
  'st. louis',
  'riverside',
  'corpus christi',
  'pittsburgh',
  'lexington',
  'anchorage',
  'stockton',
  'cincinnati',
  'st. paul',
  'toledo',
  'greensboro',
  'newark',
  'plano',
  'henderson',
  'lincoln',
  'buffalo',
  'jersey city',
  'chula vista',
  'fort wayne',
  'orlando',
  'st. petersburg',
  'chandler',
  'laredo',
  'norfolk',
  'durham',
  'madison',
  'lubbock',
  'irvine',
  'winston–salem',
  'glendale',
  'garland',
  'hialeah',
  'reno',
  'chesapeake',
  'gilbert',
  'baton rouge',
  'irving',
  'scottsdale',
  'north las vegas',
  'fremont',
  'boise',
  'richmond',
  'san bernardino',
  'birmingham',
  'spokane',
  'rochester',
  'modesto',
  'des moines',
  'fayetteville',
  'tacoma',
  'oxnard',
  'fontana',
  'montgomery',
  'moreno valley',
  'shreveport',
  'aurora',
  'yonkers',
  'akron',
  'huntington beach',
  'little rock',
  'augusta',
  'amarillo',
  'mobile',
  'grand rapids',
  'salt lake city',
  'tallahassee',
  'huntsville',
  'worcester',
  'knoxville',
  'grand prairie',
  'newport news',
  'brownsville',
  'santa clarita',
  'overland park',
  'providence',
  'jackson',
  'garden grove',
  'chattanooga',
  'oceanside',
  'fort lauderdale',
  'rancho cucamonga',
  'port st. lucie',
  'tempe',
  'ontario',
  'vancouver',
  'cape coral',
  'sioux falls',
  'springfield',
  'peoria',
  'pembroke pines',
  'elk grove',
  'salem',
  'corona',
  'eugene',
  'mckinney',
  'fort collins',
  'lancaster',
  'cary',
  'palmdale',
  'hayward',
  'salinas',
  'frisco',
  'springfield',
  'pasadena',
  'macon',
  'alexandria',
  'pomona',
  'lakewood',
  'sunnyvale',
  'escondido',
  'kansas city',
  'hollywood',
  'paterson',
  'syracuse',
  'naperville',
  'mesa',
  'dayton',
  'savannah',
  'orange',
  'pasadena',
  'fullerton',
  'hampton',
  'mcallen',
  'bellevue',
  'warren',
  'miramar',
  'west valley city',
  'othello',
  'provo',
  'cambridge',
  'denton',
  'midland',
  'waco',
  'carrollton',
  'charleston',
  'wilmington',
  'killeen',
  'topeka',
  'port st. lucie',
  'columbia',
  'hartford',
  'new haven',
  'stamford',
  'waterbury',
  'thornton',
  'mcduffie',
  'midland',
  'roanoke',
  'billings',
  'anchorage',
  'missoula',
  'greeley',
  'hilo',
  'kailua',
  'tuscaloosa',
  'hagerstown',
  'johnston',
  'thibodaux',
  'el centro',
  'tupelo',
  'biloxi',
  'rome',
  'dalton',
  'fayetteville',
  'sarasota',
  'reno',
  'kennewick',
  'new bedford',
  'erie',
  'clarksville',
  'clearwater',
  'oxford',
  'newcastle',
  'sheboygan',
  'redmond',
  'winston-salem',
  'lowell',
  'akron',
  'cumming',
  'bellingham',
  'berkeley',
  'fargo',
  'carmichael',
  'toms river',
  'beaufort',
  'bradenton',
  'flint',
  'pawtucket',
  'olympia',
  'hampton',
  'washington',
  'traverse city',
  'manchester',
  'beloit',
  'pittsfield',
  'murfreesboro',
  'escondido',
  'elizabethtown',
  'douglasville',
  'coral gables',
  'lauderhill',
  'chapel hill',
  'hickory',
  'gastonia',
  'greenwood',
  'oak park',
  'hammond',
  'portage',
  'novi',
  'canton',
  'lodi',
  'carlsbad',
  'indio',
  'hattiesburg',
  'meridian',
  'brookhaven',
  'centerville',
  'longmont',
  'grand junction',
  'carson city',
  'hammond',
  'calumet city',
  'galveston',
  'harlingen',
  'cedar hill',
  'missouri city',
  'taylor',
  'rock hill',
  'lehi',
  'orem',
  'logan',
  'utica',
  'weston',
  'pompano beach',
  'pembroke pines',
  'miramar',
  'kendall',
  'sunset',
  'doral',
  'davie',
  'tamarac',
  'lauderhill',
  'weston',
  'henderson',
  'north las vegas',
  'spring valley',
  'enterprise',
  'sparks',
  'carson city',
  'manhattan',
  'the bronx',
  'brooklyn',
  'queens',
  'staten island',
  'buffalo',
  'rochester',
  'yonkers',
  'syracuse',
  'albany',
  'new rochelle',
  'mount vernon',
  'schenectady',
  'utica',
  'white plains',
  'niagara falls',
  'brentwood',
  'levittown',
  'tonawanda',
  'west babylon',
  'freeport',
  'hempstead',
  'massapequa',
  'levittown',
  'hicksville',
  'smithtown',
  'valley stream',
  'commack',
  'bethpage',
  'new city',
  'state college',
  'wilkes-barre',
  'williamsport',
  'altoona',
  'scranton',
  'bethlehem',
  'easton',
  'hazleton',
  'johnstown',
  'chester',
  'penn hills',
  'allentown',
  'lower merion',
  'bala-cynwyd',
  'scranton',
  'state college',
  'baldwin',
  'whitehall township',
  'wilton',
  'stamford',
  'west hartford',
  'norwalk',
  'greenwich',
  'darien',
  'new britain',
  'westport',
  'ridgefield',
  'glastonbury',
  'trumbull',
  'cheshire',
  'farmington',
  'simsbury',
  'plainville',
  'tolland',
  'rockville',
  'coventry',
  'willimantic',
  'putnam',
  'west haven',
  'newington',
  'wethersfield',
  'middletown',
  'east haven',
  'north haven',
  'wallingford',
  'branford',
  'guilford',
  'north branford',
  'milford',
  'orange',
  'west haven',
  'hartford',
  'new haven',
  'new haven',
  'bridgeport',
  'new haven',
  'norwich',
  'groton',
  'london',
  'west haven',
  'cheshire village',
  'ridgefield',
  'winchester',
  'new canaan',
  'newtown',
  'new fairfield',
  'new hartford',
  'new haven',
  'new london',
  'new milford',
  'new preston',
  'newington',
  'newtown',
  'niantic',
  'noank',
  'norfolk',
  'north granby',
  'north grosvenor dale',
  'north haven',
  'north stonington',
  'north westchester',
  'norwalk',
  'norwich',
  'oakdale',
  'oakville',
  'old greenwich',
  'old lyme',
  'old mystic',
  'old saybrook',
  'orange',
  'oxford',
  'pawcatuck',
  'peach lake',
  'plainfield',
  'plainville',
  'plantsville',
  'plymouth',
  'pomfret',
  'pomfret center',
  'poquonock',
  'portland',
  'preston',
  'prospect',
  'putnam',
  'quaker hill',
  'quarryville',
  'quinebaug',
  'redding',
  'redding center',
  'ridgefield',
  'riverside',
  'rocky hill',
  'roxbury',
  'salem',
  'salisbury',
  'sandy hook',
  'sandy hook',
  'sandy hook',
  'saybrook manor',
  'scotland',
  'seymour',
  'sharon',
  'shelton',
  'sherman',
  'simpsonville',
  'somers',
  'south britain',
  'south glastonbury',
  'south kent',
  'south lyme',
  'south windham',
  'south windsor',
  'south woodstock',
  'southbury',
  'southington',
  'southport',
  'southwood acres',
  'stafford',
  'stafford springs',
  'stamford',
  'stevenson',
  'stonington',
  'storrs',
  'tokyo',
  'mosco',
];
